// Publication + education data — kept out of the React file so the user can edit easily.
window.SITE_DATA = {
  name: "Komeil Moghaddasi",
  role: "PhD Student, Computer Science",
  affiliation: "Queensland University of Technology",
  location: "Brisbane, Australia",
  tz: "Australia/Brisbane",
  email: "K.moghaddasi@qut.edu.au",
  cv: "https://komeilmoghaddasi.github.io/Komeil-Moghaddasi-CV.pdf",
  socials: [
    { label: "Scholar", href: "https://scholar.google.com/citations?user=5HM0no4AAAAJ&hl=en" },
    { label: "LinkedIn", href: "https://www.linkedin.com/in/komeil-moghaddasi" },
    { label: "ResearchGate", href: "https://www.researchgate.net/profile/Komeil-Moghaddasi" },
  ],

  intro: {
    lead: "I study how computation, energy, and intelligence can be distributed — not centralised — across the networks that will run tomorrow's cities.",
    body: "My current work at QUT focuses on decentralised grid architectures and resilient distributed power networks. Before this I spent four years building task-offloading, resource-allocation, and reinforcement-learning systems for mobile edge computing, IoT and vehicular networks — published across Q1 venues at Elsevier, IEEE and Springer.",
  },

  interests: [
    "Decentralised grid architecture",
    "Distributed energy resources",
    "Deep reinforcement learning",
    "Mobile edge computing",
    "Task offloading",
    "Vehicular networks",
    "IoT systems",
    "Optimisation algorithms",
  ],

  stats: [
    { value: 12, label: "Peer-reviewed papers" },
    { value: 8, label: "Q1 journal articles" },
    { value: 5, label: "Years researching" },
    { value: 6, label: "Co-authored venues" },
  ],

  education: [
    {
      degree: "Doctor of Philosophy, Computer Science",
      org: "Queensland University of Technology",
      where: "Brisbane, Australia",
      start: "2025",
      end: "Present",
      note: "Decentralised grid architecture & distributed power networks.",
    },
    {
      degree: "Master of Science, Information Technology",
      org: "Islamic Azad University, Urmia",
      where: "Iran",
      start: "2021",
      end: "2023",
    },
    {
      degree: "Bachelor of Science, Computer Engineering",
      org: "Islamic Azad University, Miandoab",
      where: "Iran",
      start: "2013",
      end: "2019",
    },
  ],

  publications: [
    {
      year: 2026,
      authors: ["Rahmani, A. M.", "Haider, A.", "Soleimanian Gharehchopogh, F.", "Moghaddasi, K.", "Darwesh, A.", "Hosseinzadeh, M."],
      title: "Strategic offloading in autonomous vehicles: a systematic survey of current schemes, challenges, and future prospects",
      venue: "Computer Science Review",
      publisher: "Elsevier",
      type: "survey",
      topic: "vehicular",
      tier: "Q1",
      impact: 12.7,
      href: "https://www.sciencedirect.com/science/article/abs/pii/S1574013726000079",
    },
    {
      year: 2025,
      authors: ["Moghaddasi, K.", "Rajabi, S.", "Hosseinzadeh, M."],
      title: "Intrusion detection systems for enhanced security in mobile edge computing: a systematic review",
      venue: "Wireless Personal Communications",
      publisher: "Springer",
      type: "survey",
      topic: "security",
      tier: "Q2",
      impact: 2.2,
      href: "https://link.springer.com/article/10.1007/s11277-025-11846-9",
    },
    {
      year: 2025,
      authors: ["Moghaddasi, K.", "Jurdak, R."],
      title: "An energy-aware distributed federated soft actor-critic framework for intelligent task offloading in vehicular MEC networks",
      venue: "Ad Hoc Networks",
      publisher: "Elsevier",
      type: "research",
      topic: "rl",
      tier: "Q1",
      impact: 4.8,
      href: "https://www.sciencedirect.com/science/article/abs/pii/S1570870525002914",
      first: true,
    },
    {
      year: 2025,
      authors: ["Rahmani, A. M.", "Haider, A.", "Moghaddasi, K.", "Soleimanian Gharehchopogh, F.", "Aurangzeb, K.", "Liu, Z.", "Hosseinzadeh, M."],
      title: "Self-learning adaptive power management for energy-efficient IoT–MEC systems using soft actor-critic",
      venue: "Internet of Things",
      publisher: "Elsevier",
      type: "research",
      topic: "energy",
      tier: "Q1",
      impact: 7.6,
      href: "https://www.sciencedirect.com/science/article/abs/pii/S2542660525001003",
    },
    {
      year: 2025,
      authors: ["Rahmani, A. M.", "Haider, A.", "Khoshvaght, P.", "Soleimanian Gharehchopogh, F.", "Moghaddasi, K.", "Rajabi, S.", "Hosseinzadeh, M."],
      title: "Optimising task offloading with metaheuristic algorithms across cloud, fog, and edge networks",
      venue: "Sustainable Computing",
      publisher: "Elsevier",
      type: "survey",
      topic: "offloading",
      tier: "Q1",
      impact: 5.7,
      href: "https://www.sciencedirect.com/science/article/abs/pii/S2210537924001252",
    },
    {
      year: 2025,
      authors: ["Min, H.", "Rahmani, A. M.", "Ghaderkourehpaz, P.", "Moghaddasi, K.", "Hosseinzadeh, M."],
      title: "Joint optimisation of resource allocation and multi-task offloading in high-mobility vehicular MEC",
      venue: "Ad Hoc Networks",
      publisher: "Elsevier",
      type: "research",
      topic: "vehicular",
      tier: "Q1",
      impact: 4.8,
      href: "https://www.sciencedirect.com/science/article/abs/pii/S1570870524002671",
    },
    {
      year: 2024,
      authors: ["Moghaddasi, K.", "Rajabi, S.", "Soleimanian Gharehchopogh, F.", "Ghaffari, A."],
      title: "An advanced deep RL algorithm for three-layer D2D–edge–cloud computing for efficient IoT task offloading",
      venue: "Sustainable Computing",
      publisher: "Elsevier",
      type: "research",
      topic: "rl",
      tier: "Q1",
      impact: 5.7,
      href: "https://www.sciencedirect.com/science/article/abs/pii/S2210537924000374",
      first: true,
    },
    {
      year: 2024,
      authors: ["Moghaddasi, K.", "Rajabi, S.", "Soleimanian Gharehchopogh, F."],
      title: "Multi-objective secure task offloading for blockchain-enabled IoV-MEC: a Double DQN approach",
      venue: "IEEE Access",
      publisher: "IEEE",
      type: "research",
      topic: "security",
      tier: "Q1",
      impact: 3.4,
      href: "https://ieeexplore.ieee.org/abstract/document/10378647",
      first: true,
    },
    {
      year: 2024,
      authors: ["Moghaddasi, K.", "Rajabi, S.", "Soleimanian Gharehchopogh, F."],
      title: "An enhanced Asynchronous Advantage Actor-Critic for performance optimisation in MEC-enabled IoV networks",
      venue: "Peer-to-Peer Networking and Applications",
      publisher: "Springer",
      type: "research",
      topic: "rl",
      tier: "Q2",
      impact: 3.3,
      href: "https://link.springer.com/article/10.1007/s12083-024-01633-x",
      first: true,
    },
    {
      year: 2024,
      authors: ["Moghaddasi, K.", "Rajabi, S.", "Soleimanian Gharehchopogh, F.", "Hosseinzadeh, M."],
      title: "An energy-efficient data offloading strategy for 5G-enabled vehicular edge computing using Double DQN",
      venue: "Wireless Personal Communications",
      publisher: "Springer",
      type: "research",
      topic: "vehicular",
      tier: "Q2",
      impact: 2.2,
      href: "https://link.springer.com/article/10.1007/s11277-024-10862-5",
      first: true,
    },
    {
      year: 2023,
      authors: ["Moghaddasi, K.", "Masdari, M."],
      title: "Blockchain-driven optimisation of IoT in MEC environments with deep RL and multi-criteria decision making",
      venue: "Ad Hoc Networks",
      publisher: "Elsevier",
      type: "research",
      topic: "security",
      tier: "Q1",
      impact: 4.4,
      href: "https://www.sciencedirect.com/science/article/abs/pii/S1570870523002470",
      first: true,
    },
    {
      year: 2022,
      authors: ["Moghaddasi, K.", "Rajabi, S.", "Soleimanian Gharehchopogh, F."],
      title: "A multi-objective deep RL approach for computation offloading and intelligent resource allocation in D2D–MEC",
      venue: "8th International Conference on Web Research (ICWR)",
      publisher: "IEEE",
      type: "conference",
      topic: "rl",
      tier: "Conf",
      impact: null,
      href: "https://ieeexplore.ieee.org/abstract/document/9789676",
      first: true,
    },
  ],

  topics: [
    { id: "all", label: "All" },
    { id: "energy", label: "Energy systems" },
    { id: "rl", label: "Reinforcement learning" },
    { id: "vehicular", label: "Vehicular networks" },
    { id: "offloading", label: "Task offloading" },
    { id: "security", label: "Security" },
    { id: "survey", label: "Surveys" },
  ],
};
